### PR TITLE
Better privilege handling

### PR DESCRIPTION
**Pull request by jjchico**
See issue #91.

* The script itself is now named "msctl". It can be executed by any user without root privileges.
* Default location for server and world data is $HOME/mscs
* Configuration is read from $HOME/mscs.conf or $HOME/.config/mscs/mscs.conf
* "mscs" is now a wrapper that uses "msctl" and (should) retains compatibility with old "mscs": executes under "minecraft" user, uses "/opt/mscs" as default location, reads configuration from "/etc/default/mscs".
* There is no need to "sudo mscs" anymore: "mscs" can be executed by any user with enough privileges to run "msctl" as user "minecraft". For example, this lines can be added to the "sudoers" file to allow any user in group "minecraft" to execute "mscs" as user "minecraft" without asking for a password:

  Defaults:%minecraft	!authenticate
  %minecraft		ALL = (minecraft) /usr/local/bin/msctl

* Now, "start" will not create a default world if no world exists. It will tell the user how to do so using "create". It lead to some inconsistencies like creating a default world when all worlds were disabled.
* Command line parsing infrastructure have been created. Config file (-c) and data location (-l) can now be overridden through the command line (useful for "mscs" backwards compatibility).
* Other minor changes.

Hopefully, compatibility with current "mscs" has been retained.

### CODE REVIEW

**Comment by jjchico** [comment]
With this PR a finish my particular "summer of code" with mscs. I have some additional changes in mind, including a new per-server configuration system, but they will break mscs compatibility and will need some manual migration. These additional changes  even including this PR) may better be started as an independent fork to avoid breaking current mscs installations. What do you think?

**Comment by sandain** [comment]
Looks good, thank you for all this work.  I won't have a chance to test this until later this week, but I didn't seen any problems while looking through the code.  I didn't notice any changes to the README file; there are a few things that need to be updated before this goes live, but I can take a look at that when I do the final review.

**Comment by jjchico** [comment]
I left the README until the new changes are tested.

**Comment by sandain** [comment]
I left some comments in issue #91 for this pull request.

**Pull request merged**
