### PR TITLE
Small config migration code clean-up

### PR DESCRIPTION
**Pull request by jjchico**
Encapsulate all worlds config migration code into a method to allow future re-use of the functionality and improve code readability.

### CODE REVIEW

**Comment by sandain** [comment]
Thanks for all the work you are doing.  I don't play much Minecraft any more, so I really appreciate having another developer working on the script.

**Comment by zanix** [comment]
Yes, thanks for all the updates fixes and improvements.
The [Server.properties-Examples](https://github.com/sandain/MinecraftServerControlScript/wiki/Server.properties-Examples) page in the wiki has been updated to reflect the mscs.properties changes.

I noticed some questions in the forum recently about configuration examples, should we point to the wiki from the README?

**Comment by jjchico** [comment]
You are welcome. These are my sons who play Minecraft, I am just the server admin :) But I am also starting to play a bit now that we have a family server. I am already in full iron and have a small house with nice ocean views :) However, I find hacking shell code and fighting git much more funny than playing Minecraft (sorry players).
Thank you all for all the good work with mscs.

**Comment by sandain** [comment]
I renamed the `Server.properties-Examples` page to (Server-Customization-Examples)[https://github.com/sandain/MinecraftServerControlScript/wiki/Server-Customization-Examples] and added a link to the README.

**Pull request merged**
