### PR TITLE
Fix restore

### PR DESCRIPTION
**Pull request by jjchico**
Add "--force" to rdiff-backup so that backups can be restored.
Refuse to restore if server is running.
Fix date/time listing in list-backups.

### CODE REVIEW

**Comment by zanix** [comment]
Nice, thanks for taking a look at this.
I'm almost thinking that the contents of the world should be removed before the restore because if any new files were created since the backup was made such as new regions or chunks, those files will still exist.

**Comment by jjchico** [comment]
You are right. Even better, restoration should happen in a temporary directory and only if the restoration was OK should it be moved to the original location. I will look into this.

**Comment by zanix** [comment]
That does sound better

**Comment by jjchico** [comment]
In order to fix it properly I would like to migrate the return value of some methods (like isWorld*) to proper return values instead of using stdout. I would also add sensible return values for other methods to make further development easier (like in worldBackup) so that you can do something like:

    if [ worldBackup $world ]; then
      echo "Success!"
    fi

Since it means some changes on the coding style, would it be acceptable as a PR?

**Comment by sandain** [comment]
Thanks for the fix!  I probably would have just initiated a stop sequence rather than tossing out an error message, but that works too.

**Comment by jjchico** [comment]
Thanks @sandain. This merge introduces some conflicts with my other PR. I will do a merge in the other branch.

**Pull request merged**
